dist: trusty
before_install:
  - sudo apt-get install -y ninja-build
script:
  - bash -x test.sh
  - bash -x build.sh
deploy:
  provider: releases
  api_key: $ACCESS_TOKEN
  file: ../MM-control-01-build/MM-control-01.hex
  skip_cleanup: true
  on:
    tags: true
